export enum QuestionActionTypes {
  FETCH_QUESTIONS = 'FETCH_QUESTIONS',
  FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS',
  FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR',
  SET_ANSWER = 'SET_ANSWER'
}